# Generated by Django 2.1.5 on 2019-01-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('post', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
